### ISSUE TITLE
Clustered Databases

### ISSUE THREAD

**Issue by bryanbuchanan** [yroc92/postgres-storage#2]
Hello, thanks for creating this plugin! Do you know if, and how well, it'll work with clustered Postgres instances?

**Comment by yroc92** [comment]
It depends on how your cluster is set up. If you're using a managed Postgres service (like Digital Ocean, Fly.io, etc), generally you only need to write to 1 instance and the managed service takes care of the rest. I use it like this and it works fine.

If you're clustering your Postgres instances yourself, you'll have to have some kind of proxy like managed providers do because this plugin only makes a single connection.
